# Generated by Django 5.1.3 on 2024-12-05 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0004_remove_room_room_number_room_number_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_booking.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_booking.room'),
        ),
    ]
